name: Arduino CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install AVR core
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:avr

      - name: Compile sketch for Arduino Uno
        run: |
          arduino-cli compile --fqbn arduino:avr:uno ./

      - name: Upload compiled HEX artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-uno
          path: ./build/arduino.avr.uno/*.hex
